CREATE TABLE IF NOT EXISTS user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'USER',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscription (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  keyword VARCHAR(120) NOT NULL,
  expanded_keywords JSON NULL,
  source_types JSON NULL,
  min_relevance_score INT NOT NULL DEFAULT 60,
  interval_minutes INT NOT NULL DEFAULT 30,
  enabled TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_subscription_user_enabled (user_id, enabled)
);

CREATE TABLE IF NOT EXISTS hotspot (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(500) NOT NULL,
  url VARCHAR(1000) NOT NULL,
  source VARCHAR(64) NOT NULL,
  keyword VARCHAR(120) NOT NULL,
  summary TEXT NULL,
  raw_summary TEXT NULL,
  author VARCHAR(160) NULL,
  relevance_score INT NOT NULL DEFAULT 0,
  importance VARCHAR(32) NOT NULL DEFAULT 'LOW',
  event_type VARCHAR(64) NULL,
  tags JSON NULL,
  published_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_hotspot_url (url(512)),
  INDEX idx_hotspot_keyword_created (keyword, created_at),
  INDEX idx_hotspot_importance (importance)
);

CREATE TABLE IF NOT EXISTS collector_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  source VARCHAR(64) NOT NULL,
  keyword VARCHAR(120) NOT NULL,
  status VARCHAR(32) NOT NULL,
  message TEXT NULL,
  started_at DATETIME NOT NULL,
  finished_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_analysis_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  provider VARCHAR(64) NOT NULL,
  model VARCHAR(160) NOT NULL,
  input_hash VARCHAR(64) NOT NULL,
  output_json JSON NOT NULL,
  cost_tokens INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_ai_input_hash (input_hash)
);
